version: '3.8'

services:
  app:
    container_name: smart-supply-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: smart-supply-db
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: smart_supply

volumes:
  mysql_data:

